name: Python CI with Coverage Badge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # badge için gerekli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest-cov

      - name: Run tests with coverage (HTML + terminal + JSON)
        run: |
          PYTHONPATH=src pytest --cov=src --cov-report=term-missing --cov-report=html --cov-report=json -v

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html-report
          path: htmlcov

      - name: Generate coverage badge
        uses: wouterds/github-coverage-badge-action@v1.0.1
        with:
          coverage-summary-path: coverage.json
